// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Auction defines model for Auction.
type Auction struct {
	Description *string    `json:"description,omitempty"`
	EndTime     *time.Time `json:"endTime,omitempty"`
	Id          string     `json:"id"`
	StartTime   *time.Time `json:"startTime,omitempty"`
	Title       *string    `json:"title,omitempty"`
}

// AuctionCreate defines model for AuctionCreate.
type AuctionCreate = Auction

// Bid defines model for Bid.
type Bid struct {
	Amount    float32 `json:"amount"`
	AuctionId string  `json:"auctionId"`
	Id        *string `json:"id,omitempty"`
	UserId    string  `json:"userId"`
}

// Login defines model for Login.
type Login struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Token *string `json:"token,omitempty"`
}

// Notification defines model for Notification.
type Notification struct {
	Message string `json:"message"`
	UserId  string `json:"userId"`
}

// User defines model for User.
type User struct {
	Id       *string `json:"id,omitempty"`
	Password string  `json:"password"`
	Username string  `json:"username"`
}

// PostAuctionsJSONRequestBody defines body for PostAuctions for application/json ContentType.
type PostAuctionsJSONRequestBody = AuctionCreate

// PutAuctionsAuctionIdJSONRequestBody defines body for PutAuctionsAuctionId for application/json ContentType.
type PutAuctionsAuctionIdJSONRequestBody = AuctionCreate

// PostBidsJSONRequestBody defines body for PostBids for application/json ContentType.
type PostBidsJSONRequestBody = Bid

// PostNotificationsJSONRequestBody defines body for PostNotifications for application/json ContentType.
type PostNotificationsJSONRequestBody = Notification

// PostUsersLoginJSONRequestBody defines body for PostUsersLogin for application/json ContentType.
type PostUsersLoginJSONRequestBody = Login

// PostUsersRegisterJSONRequestBody defines body for PostUsersRegister for application/json ContentType.
type PostUsersRegisterJSONRequestBody = User

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a list of all auctions
	// (GET /auctions)
	GetAuctions(c *gin.Context)
	// Create a new auction
	// (POST /auctions)
	PostAuctions(c *gin.Context)
	// Delete an auction
	// (DELETE /auctions/{auctionId})
	DeleteAuctionsAuctionId(c *gin.Context, auctionId string)
	// Get details of a specific auction
	// (GET /auctions/{auctionId})
	GetAuctionsAuctionId(c *gin.Context, auctionId string)
	// Update an auction
	// (PUT /auctions/{auctionId})
	PutAuctionsAuctionId(c *gin.Context, auctionId string)
	// Place a bid
	// (POST /bids)
	PostBids(c *gin.Context)
	// Get details of a specific bid
	// (GET /bids/{bidId})
	GetBidsBidId(c *gin.Context, bidId string)
	// Notify user of outbid
	// (POST /notifications)
	PostNotifications(c *gin.Context)
	// Login a user
	// (POST /users/login)
	PostUsersLogin(c *gin.Context)
	// Register a new user
	// (POST /users/register)
	PostUsersRegister(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAuctions operation middleware
func (siw *ServerInterfaceWrapper) GetAuctions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuctions(c)
}

// PostAuctions operation middleware
func (siw *ServerInterfaceWrapper) PostAuctions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuctions(c)
}

// DeleteAuctionsAuctionId operation middleware
func (siw *ServerInterfaceWrapper) DeleteAuctionsAuctionId(c *gin.Context) {

	var err error

	// ------------- Path parameter "auctionId" -------------
	var auctionId string

	err = runtime.BindStyledParameterWithOptions("simple", "auctionId", c.Param("auctionId"), &auctionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter auctionId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAuctionsAuctionId(c, auctionId)
}

// GetAuctionsAuctionId operation middleware
func (siw *ServerInterfaceWrapper) GetAuctionsAuctionId(c *gin.Context) {

	var err error

	// ------------- Path parameter "auctionId" -------------
	var auctionId string

	err = runtime.BindStyledParameterWithOptions("simple", "auctionId", c.Param("auctionId"), &auctionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter auctionId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuctionsAuctionId(c, auctionId)
}

// PutAuctionsAuctionId operation middleware
func (siw *ServerInterfaceWrapper) PutAuctionsAuctionId(c *gin.Context) {

	var err error

	// ------------- Path parameter "auctionId" -------------
	var auctionId string

	err = runtime.BindStyledParameterWithOptions("simple", "auctionId", c.Param("auctionId"), &auctionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter auctionId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutAuctionsAuctionId(c, auctionId)
}

// PostBids operation middleware
func (siw *ServerInterfaceWrapper) PostBids(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostBids(c)
}

// GetBidsBidId operation middleware
func (siw *ServerInterfaceWrapper) GetBidsBidId(c *gin.Context) {

	var err error

	// ------------- Path parameter "bidId" -------------
	var bidId string

	err = runtime.BindStyledParameterWithOptions("simple", "bidId", c.Param("bidId"), &bidId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bidId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBidsBidId(c, bidId)
}

// PostNotifications operation middleware
func (siw *ServerInterfaceWrapper) PostNotifications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostNotifications(c)
}

// PostUsersLogin operation middleware
func (siw *ServerInterfaceWrapper) PostUsersLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsersLogin(c)
}

// PostUsersRegister operation middleware
func (siw *ServerInterfaceWrapper) PostUsersRegister(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsersRegister(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/auctions", wrapper.GetAuctions)
	router.POST(options.BaseURL+"/auctions", wrapper.PostAuctions)
	router.DELETE(options.BaseURL+"/auctions/:auctionId", wrapper.DeleteAuctionsAuctionId)
	router.GET(options.BaseURL+"/auctions/:auctionId", wrapper.GetAuctionsAuctionId)
	router.PUT(options.BaseURL+"/auctions/:auctionId", wrapper.PutAuctionsAuctionId)
	router.POST(options.BaseURL+"/bids", wrapper.PostBids)
	router.GET(options.BaseURL+"/bids/:bidId", wrapper.GetBidsBidId)
	router.POST(options.BaseURL+"/notifications", wrapper.PostNotifications)
	router.POST(options.BaseURL+"/users/login", wrapper.PostUsersLogin)
	router.POST(options.BaseURL+"/users/register", wrapper.PostUsersRegister)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8yYzY7bNhDHX4Vge1RXdptefLNbtNiiSI00ix4CH2hxJDOVSIUz3MA1/O4FSUm2LHmz",
	"ydZqTtbHkDP8/Tkzog88M1VtNGhCvjhwzHZQiXC5dBkpo/2lkFL5a1GuranBkgLki1yUCAmvzx4duATM",
	"rKrbkbSvgS84klW64MeEg5ZvVQX+XW5sJYgvuBQE35F/mgwHKDk6D5Kw9HkzkaISRiY7JtzCB6csSL54",
	"5x1uutFm+x4y8qMbHD9ZEBRmEWX5R84X7w78Wws5X/Bv0hPLtAGZthSPm76XGEzS43WiszkmfBVX3scr",
	"KuM0nS1Cu2oL1gcooqf7cV5XMDoEOzriAkrjtxtw7m6M1u+mUHoYfi0QPxp7PRYtqmdI1FkmpxmvRvEG",
	"sDYaYRgNmb9Bj3sbTPXakMpVJtqN3Z+pAkRRwIsQd2TbycZW9IBgh+6viDspbT9K6dwMigBfru9Zbiyr",
	"hBaF0gVrtg4mbKukVLpImPfBLBQKyQbGCRNaMn1GHe94l8NtNrLl+p4n/BEsRl/zu9ndzC/P1KBFrfiC",
	"/3A3u5uH2GkXaKWtf39TQMgmT1O06cN/BVq2Np5F3EDB/vvZzP9kRhPERBR1XTYhpu8x7o6Y/UEagioM",
	"fFaR6KgKa8U+Qr2AyUqFxEzeUfSjfoxR9U3vNXnhSoZgH8EysNbYoC66qhJ2H1fKxGnKsuxNWxscobM2",
	"2MfzwQHSysj9Z5F5BpCm2B77O5Ksg+NAlvl/7XyUfrPtshCYZOiyDBBzV5Z7D+zVmA4rIVkD6UVaRRpM",
	"MA0fW5mCSbeh00NXlY/RRwmxWfUV/Dk8bzVcdpXcJ4kVFRBYDJ3N1/CQODzhsVic1f1LTZIzvpcVZTPQ",
	"69VIoWjoxrDH6D4xSBtiuXFavohxJMOEPgFOPlkj/h+Asyk3vAQSqsSJVPBVqfEYyhLDGjLfCM5Vqd1Y",
	"bXLTq/JVlL9Jd4Or5ReXvwm2z0MIr5fEvkpulYwfoVe72spb3EZS/zU/cR/rXF7ooSSrS5FN3b7W3icT",
	"/pvvpEd62CrZdKtrZdarsvJWz0rkbWP5dZTWJzT4VEn1Nrcup50WvQ/tp5Pkdc/0NtnSO21NnDZD333i",
	"5+8ZgqZp0yi438cDk8mZcdSJ6J9hWnZH76sS+lMkxiP6bfSLc0/cuPqn/RHl/LJZaYoCJFP6C7vXfGjz",
	"oIWjnbHqH3hZooYVMBHEPZc0Hoybk//Tqr5pTW8j7EOMbNKEPPkckbNFM3U3azk3xzHXxYiQOato/6eP",
	"PsJYgbBgl452/m4b7n5p/7L87a+3vOlOoX2Ft6e/L3dEdXQdYoltz9mSL3gqapU+zvlxc/w3AAD//ws1",
	"N87HFQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
